### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Aericio** [GMNetwork/GMN-Core#1]
# High Priority

- [ ] Optimize KitPvP Code

- [ ] Add SOCIALSPY SALMON ADD IT

- [ ] Deny Genisys/ImagicalMine users from using this to prevent most of the other people from using our core.

# Enhancements

- [ ] Finish CombatLog and add to GMN-Core

- [ ] Fix InvThings in its' own repo and add it to GMN-Core

**Comment by Aericio** [comment]
update!
